### PR TITLE
Meta/adding convergent evolution indication

### PR DESCRIPTION
**Pull request by xcwfwf44**
This pull requests adds convergent evolution functionality to the backend. Convergent evolution is calculated by the ConvergenceIndicator which calculates and sets a so called convergence map for mutation. This map consists of genome ID, convergence level key value pairs. A convergence level  is the distance in standard deviations of the average patristic distance of the genome compared to the average patristic distances of the other genomes. If this convergence level is above a certain threshold it is a candidate for convergent evolution and gets put in the convergence map.

### CODE REVIEW

**Comment by MatthijsRijlaarsdam** [comment]
I think we should opt for improving our existing code at this point in time, or do you think we should continue on this branch?

**Comment by xcwfwf44** [comment]
If think we should review this pull request and the merge it.

**Comment by MatthijsRijlaarsdam** [comment]
Agreed!

**Comment by MatthijsRijlaarsdam** [comment]
LGTM!

**Pull request merged**
